; Super Mario Bros. 3 Full Disassembly by Southbird 2012
; For more info, see http://www.sonicepoch.com/sm3mix/
;
; PLEASE INCLUDE A CREDIT TO THE SOUTHBIRD DISASSEMBLY
; AND THE ABOVE LINK SOMEWHERE IN YOUR WORKS :)
;
; Original disassembler source generated by DCC6502 version v1.4
; (With labels, comments, and some syntax corrections for nesasm by Southbird)
; For more info about DCC6502, e-mail veilleux@ameth.org
;
; This source file last updated: 2011-11-18 21:50:36.000000000 -0600
; Distribution package date: Fri Apr  6 23:46:16 UTC 2012

; DMC sounds are here!
; Note that due to limitation of the register, these sounds must be aligned on 64-byte ($40) boundaries
.autoimport +

.include "smb3.inc"
.include "bhop/bhop.inc"

.segment "PRGFIXED_E000"

.export Clear_Nametable_Short, DynJump, IntIRQ, IntIRQ_32PixPart_HideSprites, IntIRQ_32PixelPartition_Part3
.export IntIRQ_Finish_NoDis, IntNMI, IntReset, PRG031_F499, PRG031_FA3C, PRGROM_Change_A000, PRGROM_Change_Both2
.export PRGROM_Change_C000, PT2_Full_CHRROM_Switch, Player_GetCard, Player_GetCardAndUpdate, Player_GetItem
.export Read_Joypads, Reset_PPU_Clear_Nametables, Reset_PPU_Clear_Nametables2, Scroll_PPU_Reset
.export Sprite_RAM_Clear, StatusBar_DrawCardPiece, StatusBar_Update_Cards, VertLevel_ScreenH, VertLevel_ScreenL
.export PRGROM_Change_Both
;.export ft_sample_0, ft_sample_1, ft_sample_2, ft_sample_3, ft_sample_4

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; The following two LUTs are used together via Update_Request
    ; See index values UPDATERASTER_*
IntNMI_UpdSel_Table:
    .byte $a0   ; UPDATERASTER_32PIXPART (opt. flag UPDATERASTER_32PIXSHOWSPR)
    .byte $40   ; UPDATERASTER_SPADEGAME
    .byte $a0   ; UPDATERASTER_WATERLINE

IntNMI_Raster_Table:
    .byte $40   ; UPDATERASTER_32PIXPART (opt. flag UPDATERASTER_32PIXSHOWSPR)
    .byte $60   ; UPDATERASTER_SPADEGAME
    .byte $a0   ; UPDATERASTER_WATERLINE

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; NMI INTERRUPT
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
.proc IntNMI
    SEI      ; Prevent further masked Interrupts

    ; This pushes all the registers onto the stack
    PHP      ; Push processor status onto stack
    PHA      ; Push accumulator onto stack
    TXA      ; Reg X -> A
    PHA      ; Push A (X) onto stack
    TYA      ; Reg Y -> A
    PHA      ; Push A (Y) onto stack

    ; Push the three temp vars onto the stack
    LDA Temp_Var1
    PHA
    LDA Temp_Var2
    PHA
    LDA Temp_Var3
    PHA

    JMP PRG030_SUB_9F40  ; Jump to PRG030_SUB_9F40

PRG031_F499:
    BEQ PRG031_F4AB  ; If Update_Request = 0, goto PRG031_F4AB (no request pending)

    ; Since Update_Request must be >= 1, this converts it to a zero-based index
    AND #$7f     ; Keep lower 7 bits
    TAY      ; -> 'Y'
    DEY      ; Y-- (zero base index)

    ; Get which update path we're going to follow
    LDA IntNMI_UpdSel_Table,Y
    STA Update_Select

    ; Apply Raster_Effect as requested
    LDA IntNMI_Raster_Table,Y
    STA Raster_Effect

PRG031_F4AB:
    LDA UpdSel_Disable
    BEQ PRG031_F4B3  ; If UpdSel_Disable is not set, jump to PRG031_F4B3 (perform Update_Select activity)
    JMP PRG031_F567  ; Otherwise, jump to PRG031_F567

PRG031_F4B3:
    ; Update_Select activity begin...

    LDA Update_Select    ; Get the Update_Select value
    CMP #$80     ;
    BNE PRG031_F4BD  ; If Update_Select <> $80 (Purely vertical level), jump to PRG031_F4BD
    JMP UpdSel_Vertical  ; Otherwise, jump to UpdSel_Vertical

PRG031_F4BD:
    CMP #$40     ;
    BNE PRG031_F4C4  ; If Update_Select <> $40 (Spade Game), jump to PRG031_F4C4
    JMP UpdSel_Roulette  ; Otherwise, jump to UpdSel_Roulette

PRG031_F4C4:
    CMP #$00     ;
    BNE PRG031_F4D5  ; If Update_Select <> $00 FIXME, jump to PRG031_F4D5

    ; MMC3 event
    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #26             ; Page 26
    STA MMC3_PAGE           ; Set MMC3 page
    JMP PRG031_F610         ;

PRG031_F4D5:
    CMP #$a0     ;
    BNE PRG031_F4DC  ; If Update_Select <> $A0 (32 pixel parition), jump to PRG031_F4DC

    JMP UpdSel_32PixPart     ; Otherwise, jump to UpdSel_32PixPart

PRG031_F4DC:
    CMP #$20     ;
    BNE PRG031_F4E3  ; If Update_Select <> $20 (Title Screen), jump to PRG031_F4E3
    JMP UpdSel_Title     ; Otherwise, jump to UpdSel_Title

PRG031_F4E3:

    ; "Normal" update ($C0)

    LDA #$00     ; A = 0
    STA PPU_CTL2     ; Hide sprites and bg (most importantly)
    STA PPU_SPR_ADDR ; Resets to sprite 0 in memory
    LDA #$02     ; A = 2
    STA SPR_DMA  ; DMA sprites from RAM @ $200 (probably trying to blank them out)
    JSR PT2_Full_CHRROM_Switch   ; Set up PT2 (Sprites) CHRROM

    LDA VBlank_Tick
    BNE PRG031_F51D     ; If VBlank_Tick <> 0, jump to PRG031_F51D

    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #26             ; Page 26
    STA MMC3_PAGE           ; Set MMC3 page

    JSR Scroll_Commit_Column ; Update nametable as screen scrolls (differs from call made in UpdSel_Vertical, UpdSel_32PixPart)
    JSR Video_Misc_Updates   ; Various updates other than scrolling (palettes, status bar, etc.)
    JSR TileChng_VRAMCommit  ; Commit 16x16 tile change to VRAM

    ; Set pages at A000 and C000
    JSR PRGROM_Change_Both

    LDA Graphics_Queue
    BNE PRG031_F519     ; If we don't need to reset the graphics buffer, jump to PRG031_F519

    LDA #$00        ; Reset the graphics buffer
    STA Graphics_BufCnt
    STA Graphics_Buffer

PRG031_F519:
    LDA #$00
    STA Graphics_Queue  ; Buffer reset (if pending) not needed, we just did it ourselves

PRG031_F51D:

    LDA PPU_STAT        ; read PPU status to reset the high/low latch

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$3f        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3Fxx
    LDA #$00        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3F00 (palettes?)
    STA PPU_VRAM_ADDR   ;
    STA PPU_VRAM_ADDR   ; Now accessing $0000 (Pattern tables?)

    LDA PPU_CTL2_Copy  ; Get current PPU_CTL2 settings in RAM
    ORA #$18    ; A | 18 (BG + SPR)
    STA PPU_CTL2    ; Sprites/BG are forced to be visible regardless of PPU_CTL2_Copy

    LDA PPU_CTL1_Mod
    ORA #%10101000  ; In addition to anything else specified by PPU_CTL1_Mod, Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings
    LDA PPU_STAT    ; read PPU status to reset the high/low latch

    LDA Horz_Scroll
    STA PPU_SCROLL  ; Horizontal Scroll set
    LDA Vert_Scroll
    CLC
    ADC Vert_Scroll_Off ; Apply vertical offset (used for??)
    STA PPU_SCROLL      ; Vertical scroll set

    ; This sets the status bar scroll fix for everything after the title screen!
    ; At scanline 192, the name table scroll is fixed to always display the status bar
    LDA #192        ; A = 192
    STA MMC3_IRQCNT     ; Store 192 into the IRQ count
    STA MMC3_IRQLATCH   ; Store it into the latch (will be used later)
    STA MMC3_IRQENABLE  ; Start the IRQ counter
    CLI     ; Enable maskable interrupts

PRG031_F55B:
    ; This is a common routine used by variants

    LDA VBlank_TickEn       ; Check if VBlank occurred
    BEQ PRG031_F567  ; If A = 0, jump to PRG031_F567

    JSR Randomize       ; Seed the random number generator
    JSR Read_Joypads     ; Updates both joypads in RAM

    DEC VBlank_Tick     ; Decrement VBlank_Tick

PRG031_F567:
    ; Some jump here instead of F55B

    ; *** Bring the sound engine (page 28 and page 29) into ROM
    ;LDA #MMC3_8K_TO_PRG_C000    ; Changing PRG ROM at C000
    ;STA MMC3_COMMAND        ; Set MMC3 command
    ;LDA #39             ; Page 29
    ;STA MMC3_PAGE           ; Set MMC3 page

    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #38             ; Page 28
    STA MMC3_PAGE           ; Set MMC3 page

    ; Jump to the sound engine, newly inserted at page A000!
    ;JSR Sound_Engine_Begin
    jsr bhop_play

    ; Change A000/C000 back to whatever they were before the sound engine
    JSR PRGROM_Change_Both

    INC Counter_1   ; Simply increments every frame, used for timing

    ; Not sure what this is for
    LDA PAGE_CMD
    STA MMC3_COMMAND

    ; Pull (pop) the three temp vars from the stack
    PLA
    STA Temp_Var3
    PLA
    STA Temp_Var2
    PLA
    STA Temp_Var1

    ; This pulls (pops) all the registers from the stack...
    PLA
    TAY
    PLA
    TAX
    PLA
    PLP

    ; Fully cleaned up "NMI" interrupt
    RTI
.endproc
PRG031_F499 = IntNMI::PRG031_F499

UpdSel_Vertical:

    ; COMPARE TO PRG031_F4E3

    LDA #$00     ; A = 0
    STA PPU_CTL2     ; Hide sprites and bg (most importantly)
    STA PPU_SPR_ADDR ; Resets to sprite 0 in memory
    LDA #$02     ; A = 2
    STA SPR_DMA  ; DMA sprites from RAM @ $200 (probably trying to blank them out)
    JSR PT2_Full_CHRROM_Switch   ; Set up PT2 (Sprites) CHRROM

    LDA VBlank_Tick
    BNE PRG031_F5D3         ; If VBlank_Tick <> 0, jump to PRG031_F5D3

    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #26             ; Page 26
    STA MMC3_PAGE           ; Set MMC3 page

    JSR Scroll_ToVRAM_Apply  ; Applies Scroll_ToVRAMHi and Scroll_ToVRAMHA updates
    JSR Video_Misc_Updates   ; Various updates other than scrolling (palettes, status bar, etc.)
    JSR TileChng_VRAMCommit  ; Commit 16x16 tile change to VRAM

    ; Set pages at A000 and C000
    JSR PRGROM_Change_Both

    LDA Graphics_Queue
    BNE PRG031_F5CF     ; If we don't need to reset the buffer, jump to PRG031_F5CF

    ; Reset graphics buffer
    LDA #$00
    STA Graphics_BufCnt
    STA Graphics_Buffer

PRG031_F5CF:
    LDA #$00
    STA Graphics_Queue  ; Graphics Buffer reset

PRG031_F5D3:
    LDA PPU_STAT        ; read PPU status to reset the high/low latch

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$3f        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3Fxx
    LDA #$00        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3F00 (palettes?)
    STA PPU_VRAM_ADDR   ;
    STA PPU_VRAM_ADDR   ; Now accessing $0000 (Pattern tables?)

    LDA PPU_CTL2_Copy  ; Get current PPU_CTL2 settings in RAM
    ORA #$18    ; A | 18 (BG + SPR)
    STA PPU_CTL2    ; Sprites/BG are forced to be visible regardless of PPU_CTL2_Copy

    LDA Horz_Scroll_Hi ; ?? Can specify bits? (I think this is a mistake, and this will be zero on vertical level anyway)
    ORA #%10101000  ; Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings
    LDA PPU_STAT    ; read PPU status to reset the high/low latch

    LDA Horz_Scroll
    STA PPU_SCROLL   ; Horizontal Scroll set
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Vertical Scroll set

    LDA #192     ; A = 192
    STA MMC3_IRQCNT  ; Store 192 into the IRQ count
    STA MMC3_IRQLATCH ; Store it into the latch (will be used later)
    STA MMC3_IRQENABLE ; Start the IRQ counter
    CLI      ; Enable maskable interrupts
    JMP IntNMI::PRG031_F55B  ; Jump to PRG031_F55B

PRG031_F610:

    ; Following the "Normal" Update path...

    LDA #$00     ; A = 0
    STA PPU_CTL2     ; Hide sprites and bg (most importantly)
    STA PPU_SPR_ADDR ; Resets to sprite 0 in memory
    LDA #$02     ; A = 2
    STA SPR_DMA  ; DMA sprites from RAM @ $200 (probably trying to blank them out)
    JSR PT2_Full_CHRROM_Switch   ; Set up PT2 (Sprites) CHRROM

    LDA Map_EnterLevelFX
    BEQ PRG031_F631  ; If Map_EnterLevelFX = 0 (not entering a level), jump to PRG031_F631
    CMP #$01     ;
    BNE PRG031_F62E  ; If Map_EnterLevelFX <> 1 (only other value would be 2, during the level "opening" effect, not used in US version), jump to PRG031_F62E

    ; This is being called while level is being entered...
    JSR Map_EnterLevel_Effect   ; World map "entering" effect on page 26

    JMP PRG031_F631  ; Jump to PRG031_F631

PRG031_F62E:
    JSR Level_Opening_Effect    ; Level "opening" effect on page 26 (unused on US release)

PRG031_F631:
    LDA PPU_STAT

    LDA PPU_CTL1_Mod
    ORA #%10101000  ; In addition to anything else specified by PPU_CTL1_Mod, Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings

    LDA Horz_Scroll
    STA PPU_SCROLL   ; Horizontal Scroll set
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Vertical Scroll set

    LDA PPU_STAT        ; read PPU status to reset the high/low latch

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$3f        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3Fxx
    LDA #$00        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3F00 (palettes?)
    STA PPU_VRAM_ADDR   ;
    STA PPU_VRAM_ADDR   ; Now accessing $0000 (Pattern tables?)

    LDA PPU_CTL2_Copy  ; Get current PPU_CTL2 settings in RAM
    ORA #$18    ; A | 18 (BG + SPR)
    STA PPU_CTL2    ; Sprites/BG are forced to be visible regardless of PPU_CTL2_Copy

    LDA #%10101000  ; Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings

    LDA PPU_STAT

    LDA Horz_Scroll
    STA PPU_SCROLL   ; Horizontal Scroll set
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Vertical Scroll set

    LDA #192     ; A = 192
    STA MMC3_IRQCNT  ; Store 192 into the IRQ count
    STA MMC3_IRQLATCH ; Store it into the latch (will be used later)
    STA MMC3_IRQENABLE ; Start the IRQ counter
    CLI      ; Enable maskable interrupts
    DEC VBlank_Tick ; Decrement VBlank_Tick
    JMP IntNMI::PRG031_F567  ;

UpdSel_32PixPart:
    LDA #$00     ; A = 0
    STA PPU_CTL2     ; Hide sprites and bg (most importantly)
    STA PPU_SPR_ADDR ; Resets to sprite 0 in memory

    LDA #$02     ; A = 2
    STA SPR_DMA  ; DMA sprites from RAM @ $200 (probably trying to blank them out)
    JSR PT2_Full_CHRROM_Switch   ; Set up PT2 (Sprites) CHRROM

    LDA VBlank_Tick
    BNE PRG031_F6BC         ; If VBlank_Tick <> 0, jump to PRG031_F6BC

    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #26             ; Page 26
    STA MMC3_PAGE           ; Set MMC3 page

    JSR Scroll_Commit_Column ; Update nametable as screen scrolls (differs from call made in UpdSel_Vertical, UpdSel_32PixPart)
    JSR Video_Misc_Updates   ; Various updates other than scrolling (palettes, status bar, etc.)
    JSR TileChng_VRAMCommit  ; Commit 16x16 tile change to VRAM

    ; Set pages at A000 and C000
    JSR PRGROM_Change_Both

    LDA Graphics_Queue
    BNE PRG031_F6B8  ; If we don't need to reset the buffer, jump to PRG031_F6B8

    ; Reset graphics buffer
    LDA #$00
    STA Graphics_BufCnt
    STA Graphics_Buffer

PRG031_F6B8:
    LDA #$00
    STA Graphics_Queue ; Graphics Buffer reset

PRG031_F6BC:
    LDA PPU_STAT        ; read PPU status to reset the high/low latch

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$3f        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3Fxx
    LDA #$00        ;
    STA PPU_VRAM_ADDR   ; Access PPU address #3F00 (palettes?)
    STA PPU_VRAM_ADDR   ;
    STA PPU_VRAM_ADDR   ; Now accessing $0000 (Pattern tables?)

    LDA PPU_CTL2_Copy  ; Get current PPU_CTL2 settings in RAM
    ORA #$18    ; A | 18 (BG + SPR)
    STA PPU_CTL2    ; Sprites/BG are forced to be visible regardless of PPU_CTL2_Copy

    LDA PPU_CTL1_Mod   ; A = PPU_CTL1_Mod
    ORA #%10101000  ; In addition to anything else specified by PPU_CTL1_Mod, Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings
    LDA PPU_STAT    ; read PPU status to reset the high/low latch

    LDA Horz_Scroll
    STA PPU_SCROLL  ; Horizontal Scroll set
    LDA Vert_Scroll
    STA PPU_SCROLL  ; Vertical scroll set

    ; 32 pixel partition begins at line 160
    LDA #160
    STA MMC3_IRQCNT     ; Store 160 into the IRQ count
    STA MMC3_IRQLATCH   ; Store it into the latch (will be used later)
    STA MMC3_IRQENABLE  ; Start the IRQ counter
    CLI     ; Enable maskable interrupts
    JMP IntNMI::PRG031_F55B  ; Jump to PRG031_F55B

UpdSel_Title:
    LDA #$00     ; A = 0
    STA PPU_CTL2     ; Hide sprites and bg (most importantly)
    STA PPU_SPR_ADDR ; Resets to sprite 0 in memory
    LDA #$02     ; A = 2
    STA SPR_DMA  ; DMA sprites from RAM @ $200 (probably trying to blank them out)
    JSR PT2_Full_CHRROM_Switch   ; Set up PT2 (Sprites) CHRROM

    LDA VBlank_Tick
    BNE PRG031_F748  ; If VBlank_Tick <> 0, go to PRG031_F748

    LDA Ending2_IntCmd
    BEQ PRG031_F72B  ; If Ending2_IntCmd = 0, go to PRG031_F72B

    LDA #MMC3_8K_TO_PRG_C000    ; Changing PRG ROM at C000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #25             ; Page 25
    STA MMC3_PAGE           ; Set MMC3 page

    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #24             ; Page 24
    STA MMC3_PAGE           ; Set MMC3 page

    JSR Do_Ending2_IntCmd   ; Perform action of Ending2_IntCmd

    JMP PRG031_F748  ; Jump to PRG031_F748

PRG031_F72B:
    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA #26             ; Page 26
    STA MMC3_PAGE           ; Set MMC3 page

    JSR Video_Misc_Updates   ; Various updates other than scrolling (palettes, status bar, etc.)

    LDA Graphics_Queue
    BNE PRG031_F744  ; If we don't need to reset the graphics buffer, jump to PRG031_F744

    ; Reset graphics buffer
    LDA #$00
    STA Graphics_BufCnt
    STA Graphics_Buffer

PRG031_F744:
    LDA #$00
    STA Graphics_Queue  ; Graphics Buffer reset

PRG031_F748:
    LDA PPU_STAT

    LDA #$00
    STA PPU_VRAM_ADDR   ;
    STA PPU_VRAM_ADDR   ; Now accessing $0000 (Pattern tables?)

    LDA PPU_CTL2_Copy  ; Get current PPU_CTL2 settings in RAM
    ORA #$18    ; A | 18 (BG + SPR)
    STA PPU_CTL2    ; Sprites/BG are forced to be visible regardless of PPU_CTL2_Copy

    LDA PPU_CTL1_Mod   ; A = PPU_CTL1_Mod
    ORA #%10101000  ; In addition to anything else specified by PPU_CTL1_Mod, Generate VBlank Resets, use 8x16 sprites, sprites use PT2
    STA PPU_CTL1    ; Set above settings
    LDA PPU_STAT    ; read PPU status to reset the high/low latch

    LDA Horz_Scroll
    STA PPU_SCROLL  ; Horizontal Scroll set
    LDA Vert_Scroll
    STA PPU_SCROLL  ; Vertical scroll set

    ; NOTE: Different from the typical 192 scanline count!
    LDA #193        ; A = 193
    STA MMC3_IRQCNT     ; Store 193 into the IRQ count
    STA MMC3_IRQLATCH   ; Store it into the latch (will be used later)
    STA MMC3_IRQENABLE  ; Start the IRQ counter
    CLI     ; Enable maskable interrupts

    LDA VBlank_TickEn   ; Check VBlank flag
    BEQ PRG031_F786     ; If A = 0, jump to PRG031_F786
    JSR Randomize       ; Shake up the randomizer!
    JSR Read_Joypads     ; Updates both joypads in RAM

    DEC VBlank_Tick     ; Decrement VBlank_Tick

PRG031_F786:
    JMP IntNMI::PRG031_F567  ; Jump to PRG031_F567

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Set of pages "normal" IRQ sets when tileset is 0 (World Map) or 7 (Toad House)
StatusBarMTCHR_0000:    .byte $5c   ; Standard status bar part 1 ($5C and $5D are loaded)
StatusBarMTCHR_0800:    .byte $5e   ; Standard status bar part 2 ($5E and $5F are loaded)
SpriteMTCHR_1000:   .byte $48
SpriteMTCHR_1400:   .byte $49
SpriteMTCHR_1800:   .byte $05   ; Power-up and Toad sprites here
SpriteMTCHR_1C00:   .byte $4b

; Set of pages "normal" IRQ sets (for status bar I presume)
StatusBarCHR_0000:  .byte $5c   ; Standard status bar part 1 ($5C and $5D are loaded)
StatusBarCHR_0800:  .byte $5e   ; Standard status bar part 2 ($5E and $5F are loaded)
SpriteHideCHR_1000: .byte $7e   ; ALL BLANK TILES
SpriteHideCHR_1400: .byte $7e   ; ALL BLANK TILES
SpriteHideCHR_1800: .byte $7e   ; ALL BLANK TILES
SpriteHideCHR_1C00: .byte $7e   ; ALL BLANK TILES

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IntIRQ:  ; $F795 IRQ Interrupt (scanline from MMC3)
    SEI      ; Disable maskable interrupts

    ; Save all registers
    PHP      ; Push processor status onto stack
    PHA      ; Push accumulator onto stack
    TXA      ; Reg X -> A
    PHA      ; Push A (X) onto stack
    TYA      ; Reg Y -> A
    PHA      ; Push A (Y) onto stack

    LDA Reset_Latch
    CMP #$5a
    BEQ PRG031_F7B0  ; If Reset_Latch = $5A, go to PRG031_F7B0

    ; Reset_Latch was something other than the magic $5A value... reset!!

    ; This gets the address of the Reset entry point -> [Temp_Var2][Temp_Var1]
    LDA Vector_Table+2
    STA Temp_Var1
    LDA Vector_Table+3
    STA Temp_Var2

    ; Jump to the Reset instead...
    JMP (Temp_Var1)

PRG031_F7B0:
    ;LDA PAPU_MODCTL_Copy
    ;PHA      ; Save A
    ;AND #$7f     ; Basically don't disturb DMC, but disable interrupt, if active
    ;STA PAPU_MODCTL  ;

    LDA Raster_Effect    ; Get status bar mode

    CMP #$80     ; Are we in "do nothing" mode?
    BNE PRG031_F7C3  ; If not, go to PRG031_F7C3
    JMP IntIRQ_Finish    ; Otherwise, jump to IntIRQ_Finish (nothing to do!)

PRG031_F7C3:
    CMP #$40     ; Are we in "32 pixel partition" mode?
    BNE PRG031_F7CA ; If not, go to PRG031_F7CA
    JMP IntIRQ_32PixelPartition  ; Otherwise, jump to IntIRQ_32PixelPartition

PRG031_F7CA:
    CMP #$20     ; Are we in "title screen" mode? (used on title screen and ending sequence)
    BNE PRG031_F7D1  ; If not, go to PRG031_F7D1
    JMP IntIRQ_TitleEnding   ; Otherwise, jump to IntIRQ_TitleEnding

PRG031_F7D1:
    CMP #$60     ; Are we in "Spade Game" mode?
    BNE PRG031_F7D8  ; If not, go to PRG031_F7D8
    JMP IntIRQ_SpadeGame     ; Otherwise, jump to IntIRQ_SpadeGame

PRG031_F7D8:
    CMP #$A0     ; Are we in "A0??? FIXME" mode? ()
    BNE PRG031_F7DF  ; If not, go to PRG031_F7DF
    JMP IntIRQ_A0FIXME   ; Otherwise, jump to IntIRQ_A0FIXME

PRG031_F7DF:

    ; Flags for vertical World 7 speciality levels
    LDA Level_7Vertical
    BEQ IntIRQ_Vertical  ; For vertical type levels
    JMP IntIRQ_Standard  ; Otherwise, just do the standard thing (status bar used in level and map)

IntIRQ_Vertical:
    STA MMC3_IRQENABLE ; Active IRQ
    NOP      ;
    NOP      ;
    NOP      ;
    LDY #$0b     ; Y = $0B
    LDA Level_Tileset ; A = current tileset
    CMP #17
    BNE PRG031_F7F8  ; If tileset <> 17 (N-Spade), jump to PRG031_F7F8
    LDY #$03     ; Y = $03

PRG031_F7F8:
    LDX #$00     ; X = 0

    CMP #$00     ;
    BEQ PRG031_F871  ; If tileset = 0 (World map), go to PRG031_F871
    CMP #$07     ;
    BEQ PRG031_F871  ; If tileset = 7 (Toad house), go to PRG031_F871
    CMP #17
    BEQ PRG031_F871  ; If tileset = 17 (N-Spade), go to PRG031_F871

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$00
    STA PPU_VRAM_ADDR
    LDA #$00
    STA PPU_VRAM_ADDR
    STA PPU_VRAM_ADDR
    STA PPU_VRAM_ADDR

    STX PPU_CTL2     ; Sprites + BG invisible
    LDA PPU_STAT     ;

    ; Because vertical scroll will not change after frame begins (second write to
    ; PPU_SCROLL will always be unused until next frame), the hack for MMC3 split
    ; vertical scrolling is to change the nametable address that the PPU is reading
    ; at to where we would like it to be...
    ; In this case, the location of the beginning of the status bar!
    STY PPU_VRAM_ADDR    ; This is $0B unless tileset = $11, which it is then $03
    LDA #$00
    STA PPU_VRAM_ADDR   ; ... so we're now reading at $1100 or $0300
    LDA PPU_VRAM_DATA

    ; Load status bar graphics and hide any sprites from appearing over the status bar

    ; Load two parts of Status Bar
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarCHR_0800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND

    ; Use blank tiles for all sprite graphics
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

    LDA #$18     ;
    STA PPU_CTL2     ; Sprites + BG now visible
    JMP PRG031_F8B3

PRG031_F871:
    ; World map / Toad House / N-Spade

    ; Load status bar graphics and hide any sprites from appearing over the status bar

    ; Load two parts of Status Bar
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarMTCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarMTCHR_0800

    ; Load sprite graphics appropriate for World Map / Toad House / N-Spade
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1C00
    STA MMC3_PAGE

PRG031_F8B3:
    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Store result into actual register
    LDA PPU_STAT     ;

    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal Scroll = 0
    LDA Vert_Scroll ;
    STA PPU_SCROLL   ; Vertical Scroll updated

IntIRQ_Finish:
    STA MMC3_IRQDISABLE ; Disable the IRQ generation

IntIRQ_Finish_NoDis:
    LDA PAGE_CMD     ; Get old page command
    STA MMC3_COMMAND ; Issue it
    ;PLA      ; Restore A (PAPU_MODCTL_Copy)
    ;STA PAPU_MODCTL  ; Set DMC back to normal

    ; Restore the other registers
    PLA
    TAY
    PLA
    TAX
    PLA
    PLP

    RTI      ; End of IRQ interrupt!

IntIRQ_Standard:    ; $F8DB
    STA MMC3_IRQENABLE ; Enable IRQ generation

    ; Some kind of delay loop?
    LDX #$02     ; X = 2
PRG031_F8E0:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_F8E0  ; While X > 0, loop

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$00
    STA PPU_VRAM_ADDR
    LDX #$00
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR

    STX PPU_CTL2     ; Hide BG + Sprites
    LDA PPU_STAT     ;

    ; Because vertical scroll will not change after frame begins (second write to
    ; PPU_SCROLL will always be unused until next frame), the hack for MMC3 split
    ; vertical scrolling is to change the nametable address that the PPU is reading
    ; at to where we would like it to be...
    LDY #$07
    STY PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR   ; ... so we're now reading at $0700
    LDA PPU_VRAM_DATA

    ; Couple of tilesets have slightly different effects
    LDA Level_Tileset
    CMP #$00     ;
    BEQ PRG031_F955  ; If A = 0 (On world map), go to PRG031_F955
    CMP #$07     ;
    BEQ PRG031_F955  ; If A = 7 (Toad house), go to PRG031_F955
    ; But not N-Spade?

    ; Load status bar graphics and hide any sprites from appearing over the status bar

    ; Load two parts of Status Bar
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarCHR_0800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND

    ; Use blank tiles for all sprite graphics
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

    JMP PRG031_F997  ; Jump to PRG031_F997

PRG031_F955:
    ; World Map and Toad House alternate (but not N-Spade?)

    ; Load status bar graphics and hide any sprites from appearing over the status bar

    ; Load two parts of Status Bar
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarMTCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarMTCHR_0800
    STA MMC3_PAGE

    ; Load sprite graphics appropriate for World Map / Toad House / N-Spade
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteMTCHR_1C00
    STA MMC3_PAGE

PRG031_F997:
    LDA #$18     ; A | 18 (BG + SPR)
    STA PPU_CTL2     ; Sprites/BG are visible
    LDA PPU_CTL1_Copy   ; PPU_CTL1 copy
    ORA #$01     ; Force $2400 nametable address
    STA PPU_CTL1     ; Set it in the register
    LDA PPU_STAT     ;
    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal scroll = 0
    LDA Vert_Scroll ;
    STA PPU_SCROLL   ; Vertical scroll update as-is
    JMP IntIRQ_Finish    ; Clean up IRQ

IntIRQ_32PixelPartition:    ; $F9B3

    ; Lotta no-ops??
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP

    LDA Raster_State ; Get current state of the Raster op
    BEQ PRG031_F9C1  ; If Raster_State = 0, go to PRG031_F9C1 (at the 32 pixel partition)
    JMP PRG031_FA3F  ; Otherwise, jump to PRG031_FA3F (below the 32 pixel partition, status bar)

PRG031_F9C1:
    ; At the 32 pixel partition

    ; Some kind of delay loop?
    LDX #$15     ; X = $15
PRG031_F9C3:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_F9C3 ; While X > 0, loop

    LDA #$10     ;
    STA PPU_CTL2     ; Only show sprites (?)
    LDA PPU_STAT     ;

    ; Because vertical scroll will not change after frame begins (second write to
    ; PPU_SCROLL will always be unused until next frame), the hack for MMC3 split
    ; vertical scrolling is to change the nametable address that the PPU is reading
    ; at to where we would like it to be...
    LDY #$0a     ; Y = $0A
    LDA #$80     ; A = $80
    STY PPU_VRAM_ADDR    ;
    STA PPU_VRAM_ADDR    ; ... so we're now reading at $0A80, the top of the last two rows of tiles
    LDA PPU_VRAM_DATA    ;

    JMP IntIRQ_32PixelPartition_Part2   ; Jump to IntIRQ_32PixelPartition_Part2

    ; Something removed?
    NOP
    NOP
    NOP
    NOP

IntIRQ_32PixPart_HideSprites:   ; $F9E3

    ; This part is skippable based on a flag; only loads
    ; Pattern Table 2 in this case...
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE


IntIRQ_32PixelPartition_Part3:
    LDA PPU_STAT
    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Stored to the register!

    LDA Horz_Scroll
    STA PPU_SCROLL   ; Set horizontal scroll
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Set vertical scroll

    LDA #$18     ;
    STA PPU_CTL2     ; BG + Sprites now visible

    INC Raster_State ; Raster_State = 1

    LDA #27      ;
    STA MMC3_IRQCNT  ; Next interrupt in 27 lines
    STA MMC3_IRQDISABLE  ; Disable IRQ...
    JMP IntIRQ_32PixelPartition_Part5    ; Jump to IntIRQ_32PixelPartition_Part5

    ; Dead code?  Or maybe timing/cycle filler
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP

PRG031_FA3C:
    JMP IntIRQ_Finish_NoDis  ; Jump to IntIRQ_Finish_NoDis

PRG031_FA3F:
    ; The part we do when Raster_State = 1 (the 2nd IRQ interrupt split)

    ; Some kind of delay loop?
    LDX #$05     ; X = 5
PRG031_FA41:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_FA41 ; While X > 0, loop

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$00
    STA PPU_VRAM_ADDR
    LDX #$00
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR

    STX PPU_CTL2     ; Sprites + BG hidden
    LDA PPU_STAT     ;

    ; Because vertical scroll will not change after frame begins (second write to
    ; PPU_SCROLL will always be unused until next frame), the hack for MMC3 split
    ; vertical scrolling is to change the nametable address that the PPU is reading
    ; at to where we would like it to be...
    LDY #$0b
    STY PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR   ; ... so now we're reading at $0B00
    LDA PPU_VRAM_DATA

    ; This loads graphics into the "BG" side (PT1)
    ; I think the only reason they're using labeled constants
    ; is so they could put this code in multiple spots, but it'd
    ; stay in sync if they needed to change the CHRROM banks.
    ; But that'd be the job of an assembler label, wouldn't it??
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarCHR_0800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

    LDA #$18     ;
    STA PPU_CTL2     ; Sprites + BG now visible
    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Update the PPU_CTL1 register..
    LDA PPU_STAT     ;

    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal scroll locked at zero
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Vertical scroll as-is
    LDA #$00     ;
    STA Raster_State ; Clear Raster_State (no more effects)
    JMP IntIRQ_Finish    ; Clean up IRQ


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Tables used by IntIRQ_SpadeGame
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Roulette_RasterDelay:
    .byte $02, $02, $02, $06

    ; This table tells how many lines to skip to the next row.
    ; Apparently they didn't really take advantage of the potential
    ; for this functionality, however, as all values are equal!
Roulette_RasterDiv: ; Raster_State = 0,1,2
    .byte $34, $34, $34

    .byte $00   ; Not used, would be Raster_State = 3

IntIRQ_SpadeGame:

    ; Disable then enable the IRQ??  Probably to make sure
    ; last latch value gets pushed into counter...
    STA MMC3_IRQDISABLE
    STA MMC3_IRQENABLE

    LDY Raster_State ; Get current Raster_State
    CPY #$03     ;
    BEQ PRG031_FAE7  ; If Raster_State = 3, jump to PRG031_FAE7

    ; Based on the current Raster_State, set next scanline delay
    LDA Roulette_RasterDiv,Y
    STA MMC3_IRQCNT
    STA MMC3_IRQENABLE

PRG031_FAE7:

    ; Another of these common delay loops, this time dynamic...
    LDX Roulette_RasterDelay,Y   ; Get value based on Raster_State
PRG031_FAEA:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_FAEA  ; While > 0, loop...

    CPY #$03     ;
    BNE PRG031_FB34  ; If Raster_State <> 3, jump to PRG031_FB34

    ; Raster_State = 3 (load status bar graphics)

    ; This loads graphics into the "BG" side (PT1)
    ; I think the only reason they're using labeled constants
    ; is so they could put this code in multiple spots, but it'd
    ; stay in sync if they needed to change the CHRROM banks.
    ; But that'd be the job of an assembler label, wouldn't it??
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarCHR_0800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

PRG031_FB34:
    LDA PPU_STAT     ;

    CPY #$03     ;
    BEQ PRG031_FB57  ; If Raster_State = 3, jump to PRG031_FB57

    ; Raster_State < 3...

    LDA Roulette_PosHi,Y     ; Get position for this row
    AND #$01     ; Nametable swaps $2000 / $2400 every odd/even unit (??)
    ORA PPU_CTL1_Copy  ; Update PPU_CTL1_Copy
    STA PPU_CTL1        ; .. and the actual PPU_CTL1 register
    LDA Roulette_Pos,Y   ; Get horizontal scroll position for this row
    STA PPU_SCROLL   ; Store the horizontal
    LDA #$00     ;
    STA PPU_SCROLL   ; Vertical = 0
    INY      ;
    STY Raster_State ; Raster_State++
    JMP IntIRQ_Finish_NoDis  ; Cleanup and finish (for THIS Raster_State)

PRG031_FB57:
    ; Raster_State = 3 ...
    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Update actual register
    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal Scroll = 0
    LDA Vert_Scroll ;
    STA PPU_SCROLL   ; Vertical Scroll updated (should generally not be moving here :)
    LDA #$00     ;
    STA Raster_State     ; Raster_State = 0
    JMP IntIRQ_Finish    ; Clean up IRQ, we're done!


    ; FIXME: What is this for??
IntIRQ_A0FIXME:
    ; Disable then enable the IRQ??  Probably to make sure
    ; last latch value gets pushed into counter...
    STA MMC3_IRQDISABLE
    STA MMC3_IRQENABLE

    LDA Raster_State
    BEQ PRG031_FB7E ; If Raster_State = 0, go to PRG031_FB7E
    JMP PRG031_FBE5 ; Otherwise, jump to PRG031_FBE5

PRG031_FB7E:
    ; Some kind of delay loop?
    LDX #$14     ; X = $14
PRG031_FB80:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_FB80 ; While X > 0, loop

    LDA #$10     ;
    STA PPU_CTL2     ; Only show sprites

    ; Only loads Pattern Table 2 in this case...
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

    LDA PPU_STAT
    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Update the actual register

    LDA Horz_Scroll
    STA PPU_SCROLL   ; Update Horizontal Scroll
    LDA Vert_Scroll
    STA PPU_SCROLL   ; Update Vertical Scroll
    INC Raster_State ; Raster_State++

    LDA #27
    STA MMC3_IRQCNT  ; Next IRQ in 27 lines

    ; Some kind of delay loop?
    LDX #$02     ; X = $14
PRG031_FBD3:
    NOP      ; ?
    DEX      ; X--
    BPL PRG031_FBD3 ; While X >= 0, loop

    LDA #$18     ;
    STA PPU_CTL2     ; Sprites + BG now visible

    ; Dead code?  Or timing/cycle filler
    NOP
    NOP
    NOP

    ; The following JSR does a delay then updates the IRQ
    ; counter latch and Resets it
    JSR PRG030_SUB_9F50
    JMP IntIRQ_Finish_NoDis  ; Clean up for THIS Raster_State...

PRG031_FBE5:
    ; Raster_State <> 0...

    ; Some kind of delay loop?
    LDX #$03     ; X = $14
PRG031_FBE7:
    NOP      ; ?
    DEX      ; X--
    BNE PRG031_FBE7 ; While X > 0, loop

    ; Unknown hardware thing?  Is this for synchronization?
    LDA #$00
    STA PPU_VRAM_ADDR
    LDX #$00
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR

    STX PPU_CTL2     ; Most importantly, hide BG + Sprites
    LDA PPU_STAT     ;

    ; Because vertical scroll will not change after frame begins (second write to
    ; PPU_SCROLL will always be unused until next frame), the hack for MMC3 split
    ; vertical scrolling is to change the nametable address that the PPU is reading
    ; at to where we would like it to be...
    LDY #$0b
    STY PPU_VRAM_ADDR
    STX PPU_VRAM_ADDR   ; ... so now we're reading at $0B00
    LDA PPU_VRAM_DATA

    ; This loads graphics into the "BG" side (PT1)
    ; I think the only reason they're using labeled constants
    ; is so they could put this code in multiple spots, but it'd
    ; stay in sync if they needed to change the CHRROM banks.
    ; But that'd be the job of an assembler label, wouldn't it??
    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND
    LDA StatusBarCHR_0000
    STA MMC3_PAGE
    LDA #MMC3_2K_TO_PPU_0800
    STA MMC3_COMMAND
    LDA StatusBarCHR_0800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1000
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1000
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1400
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1400
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1800
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1800
    STA MMC3_PAGE
    LDA #MMC3_1K_TO_PPU_1C00
    STA MMC3_COMMAND
    LDA SpriteHideCHR_1C00
    STA MMC3_PAGE

    LDA #$18     ;
    STA PPU_CTL2     ; Sprites + BG now visible

    LDA PPU_CTL1_Copy
    ORA PPU_CTL1_Mod   ; Combine bits from PPU_CTL1_Copy into PPU_CTL1_Mod
    STA PPU_CTL1     ; Update the actual register
    LDA PPU_STAT     ;

    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal Scroll = 0
    LDA Vert_Scroll ;
    STA PPU_SCROLL   ; Update Vertical Scroll
    LDA #$00     ;
    STA Raster_State     ; Raster_State = 0
    JMP IntIRQ_Finish    ; Clean up IRQ


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PRGROM_Change_Both
;
; This subroutine sets both PRG ROM pages A000 and C000 together.
;   C000 is set to the page value found at RAM location PAGE_C000
;   A000 is set to the page value found at RAM location PAGE_A000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PRGROM_Change_Both: ; $FC6F

    ; Setting PRG ROM C000 to page specified in PAGE_C000
    LDA #MMC3_8K_TO_PRG_C000    ; Changing PRG ROM at C000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA PAGE_C000           ; Page @ PAGE_C000
    STA MMC3_PAGE           ; Set MMC3 page

    ; Setting PRG ROM A000 to page specified in PAGE_A000
    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA PAGE_A000           ; Page @ PAGE_A000
    STA MMC3_PAGE           ; Set MMC3 page

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ; Split arrays defining the vertical screen starting positions
    ; (i.e. $000, $0F0, $1E0, $2D0, ...)
VertLevel_ScreenH:  .byte $00, $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0A, $0B, $0C, $0D, $0E
VertLevel_ScreenL:  .byte $00, $F0, $E0, $D0, $C0, $B0, $A0, $90, $80, $70, $60, $50, $40, $30, $20, $10

; This stores the four tiles which make up a card (or absense of one)
;              -    M    F    S
CardUL: .byte $FE, $E0, $E4, $AC
CardUR: .byte $FE, $E1, $E6, $AD
CardLL: .byte $FE, $E2, $E7, $AE
CardLR: .byte $FE, $E3, $E8, $AF

; Each card's video start offset (lower byte)
CardVStartU:    .byte $36, $39, $3C ; Upper half of card
CardVStartL:    .byte $56, $59, $5C ; Lower half of card

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Player_GetCardAndUpdate
;
; This subroutine gives Player a card (see Player_GetCard)
; and updates their status bar (see StatusBar_Update_Cards)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Player_GetCardAndUpdate:
    JSR Player_GetCard

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; StatusBar_Update_Cards
;
; This subroutine prepares the three cards in the Player's
; inventory, storing them into the graphics buffer to be
; drawn when ready...
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
StatusBar_Update_Cards:
    LDA Player_Current
    BEQ PRG031_FCC6  ; If player = 0 (Mario), jump to PRG031_FCC6
    LDA #Inventory_Cards2 - Inventory_Cards

PRG031_FCC6:
    ; A is 0 (Mario) or $23 (Luigi)

    STA Temp_Var1   ; Temp_Var1 = A

    LDA #$02
    STA Temp_Var2   ; Temp_Var2 = 2

PRG031_FCCC:
    LDY Temp_Var1   ; Y = Temp_Var1

    JSR StatusBar_DrawCardPiece  ; Draw part of the card into the status bar

    INC Temp_Var1
    DEC Temp_Var2
    BPL PRG031_FCCC  ; While Temp_Var2 >= 0, loop!

    RTS      ; Return

StatusBar_DrawCardPiece:
    STY Temp_Var3      ; Temp_Var3 = Y
    LDX Inventory_Cards,Y   ; Get next card

    LDY Graphics_BufCnt     ; Current position within graphics buffer

    ; Store the upper tiles of the card in the buffer
    LDA CardUL,X
    STA Graphics_Buffer+3,Y
    LDA CardUR,X
    STA Graphics_Buffer+4,Y

    ; Store the lower tiles of the card in the buffer
    LDA CardLL,X
    STA Graphics_Buffer+8,Y
    LDA CardLR,X
    STA Graphics_Buffer+9,Y

    LDX Player_Current  ; X = Player_Current
    BEQ PRG031_FCFF     ; If player = 0 (Mario), jump to PRG031_FCFF
    LDX #Inventory_Cards2 - Inventory_Cards
PRG031_FCFF:

    LDA Temp_Var3      ; A = Temp_Var3 (offset to current card)
    STX Temp_Var3      ; Temp_Var3 = X
    SEC
    SBC Temp_Var3      ; A -= Temp_Var3 (offset from start to current card)
    TAX         ; A = X

    LDA CardVStartU,X
    STA Graphics_Buffer+1,Y

    LDA CardVStartL,X
    STA Graphics_Buffer+6,Y

    LDA #$2b     ; A = $2B (Not vertical)

    LDX Level_7Vertical
    BEQ PRG031_FD1C  ; If level is not vertical, jump to PRG031_FD1C

    LDA #$27     ; A = $27 (Vertical)
PRG031_FD1C:
    LDX Level_Tileset
    CPX #16
    BEQ PRG031_FD27  ; If Level_Tileset = 16 (Spade game), jump to PRG031_FD27

    CPX #17
    BNE PRG031_FD29  ; If Level_Tileset = 17 (N-Spade), jump to PRG031_FD29

PRG031_FD27:
    LDA #$23     ; A = $23 (Spade game)

PRG031_FD29:

    ; Configure graphics buffer
    STA Graphics_Buffer,Y
    STA Graphics_Buffer+5,Y

    LDA #$02
    STA Graphics_Buffer+2,Y
    STA Graphics_Buffer+7,Y

    ; Terminate
    LDA #$00
    STA Graphics_Buffer+$A,Y

    ; Set buffer count
    TYA
    CLC
    ADC #$0a
    STA Graphics_BufCnt

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Player_GetCard
;
; Gives the Player a card, specified in 'A'
; A = 0 (Mushroom), 1 = (Flower), 2 = (Star)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Player_GetCard:
    PHA      ; Save which card we're getting

    LDY Player_Current
    BEQ PRG031_FD4C  ; If Player is Mario, jump to PRG031_FD4C

    LDY #Inventory_Cards2 - Inventory_Cards

PRG031_FD4C:
    LDA Inventory_Cards,Y
    BEQ PRG031_FD67  ; If this card is empty, jump to PRG031_FD67

    INY      ; Y++
    CPY #$03
    BEQ PRG031_FD5A  ; If Mario's cards are full, jump to PRG031_FD5A
    CPY #Inventory_Cards2 - Inventory_Cards + 3
    BNE PRG031_FD4C  ; If Luigi's cards are NOT full, jump to PRG031_FD4C

PRG031_FD5A:

    ; Rotate cards through
    LDA Inventory_Cards-2,Y
    STA Inventory_Cards-3,Y
    LDA Inventory_Cards-1,Y
    STA Inventory_Cards-2,Y

    DEY      ; Y--

PRG031_FD67:
    PLA      ; Restore the card we're going to get
    STA Inventory_Cards,Y    ; Store the new card

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Player_GetItem
;
; Gives Player an item specified in 'A'
; If Inventory is full, goes at the end.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Player_GetItem:
    PHA      ; Save input item

    LDY Player_Current
    BEQ PRG031_FD74  ; If not Luigi, jump to PRG031_FD74

    LDY #Inventory_Items2 - Inventory_Items   ; Luigi inventory offset

PRG031_FD74:
    LDX #Inventory_Cards - Inventory_Items - 1    ; X = total inventory slots
PRG031_FD76:
    LDA Inventory_Items,Y
    BEQ PRG031_FD7F  ; If this slot is empty, jump to PRG031_FD7F

    INY      ; Y++ (next slot over)
    DEX      ; X-- (one less item slot total)
    BNE PRG031_FD76  ; If X > 0, loop!

PRG031_FD7F:
    PLA      ; Restore the target item
    STA Inventory_Items,Y    ; Give it to the Player!

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sprite_RAM_Clear
;
; This subroutine clears the local copy of OAM by filling
; the X/Y values in with $F8 and $01, essentially making
; them all invisible until actually needed
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Sprite_RAM_Clear:   ; $FD84
    LDY #$00     ; Y = 0

PRG031_FD86:
    LDA #$f8        ; A = $F8
    STA Sprite_RAM,  Y  ; Next X value
    LDA #$01        ; A = $01
    STA Sprite_RAM+1,Y  ; Next Y value
    INY      ;
    INY      ;
    INY      ;
    INY      ; Y += 4
    BNE PRG031_FD86  ; While Y does not equal zero (covers all 256 bytes)

    RTS      ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Scroll_PPU_Reset
;
; This subroutine Resets the scroll position of the nametable
; and its associated variables back to zero, and also reasserts
; that the PPU is displaying sprites in PT2, but interestingly
; does not set them to 8x16 ??
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Scroll_PPU_Reset:   ; $FD97
    LDA #$00     ;
    STA PPU_SCROLL   ; Horizontal scroll = 0
    STA Horz_Scroll ; Horz_Scroll = 0
    STA PPU_SCROLL   ; Vertical scroll = 0
    STA Vert_Scroll ; Vert_Scroll = 0
    LDA #$08     ;
    STA PPU_CTL1     ; Sprites in PT2
    RTS      ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Reset_PPU_Clear_Nametables
;
; Resets PPU_CTL2 and clears both nametables and also resets
; the graphics buffer in case any updates were pending...
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Reset_PPU_Clear_Nametables: ; $FDA9
    ; Reset graphics buffer
    LDA #$00
    STA Graphics_BufCnt
    STA Graphics_Buffer

Reset_PPU_Clear_Nametables2:
    ; NMI PPU_CTL2 and clear both nametables
    JSR Clear_PPU_CTL2_Copy ; Clear RAM copy and actual PPU_CTL2
    LDA #$20        ; Select Nametable 0
    JSR Clear_Nametable ; Clear nametable to all $FC
    LDA #$28        ; Select Nametable 2
    JSR Clear_Nametable ; Clear nametable to all $FC
    RTS         ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Clear_PPU_CTL2_Copy
;
; Clears the PPU_CTL2_Copy variable and also the
; PPU_CTL2 register itself
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Clear_PPU_CTL2_Copy:    ; $FDBF
    LDA #$00
    STA PPU_CTL2_Copy  ; Clears PPU_CTL2_Copy (though sprites/BG overridden as visible anyway)
    STA PPU_CTL2        ; At this point, clearing PPU_CTL2 altogether, though likely it will shortly be updated
    RTS         ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Clear_Nametable
;
; This subroutine clears an entire nametable, specified by
; the initial value of A ($20 for NT 0, $28 for NT2, and
; technically the other two could be specified as well)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Clear_Nametable:    ; $FDC7:
    STA Temp_Var1      ; Save A

    LDA PPU_STAT        ;
    LDA #$00        ;
    STA PPU_CTL1        ; Most likely most importantly to prevent any more Resets

    LDA Temp_Var1      ; Restore A (from Reset_PPU_Clear_Nametables, this is $20 or $28, Nametable 0 or Nametable 2)
    STA PPU_VRAM_ADDR   ; Write this as high byte VRAM address select
    LDA #$00
    STA PPU_VRAM_ADDR   ; $00 as low byte for VRAM address (Reset_PPU_Clear_Nametables selects nametable 1 or 2)

    ; This writes over the entire selected name table and attribute table with $FC
    LDX #$04     ; X = $04
    LDY #$00     ; Y = $00
    LDA #$fc     ; A = $FC
PRG031_FDE1:
    STA PPU_VRAM_DATA    ; Write $FC to NT
    DEY      ; Y--
    BNE PRG031_FDE1  ; While <> 0, loop (will write 256 times)
    DEX      ; X--
    BNE PRG031_FDE1  ; While <> 0, loop (will write 4 times)

    LDA Temp_Var1   ; Retrieve initial A value again
    CLC
    ADC #$03        ; A += 3 (moving to attribute table)
    STA PPU_VRAM_ADDR   ; Address high byte
    LDA #$c0        ; Beginning of attribute table
    STA PPU_VRAM_ADDR   ; Address low byte

    ; This will write over the attribute table (technically the prior loop does an
    ; unnecessary overrun... probably just a simpler loop to code.)
    LDY #$40     ; Y = $40
    LDA #$00     ; A = 0
PRG031_FDFB:
    STA PPU_VRAM_DATA    ; Write $00 to AT
    DEY      ; Y--
    BNE PRG031_FDFB  ; While Y <> 0, loop (will write 64 times)

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Clear_Nametable_Short
;
; This subroutine sets ClearPattern over half a nametable, which
; is the initial value of A ($20 for NT 0, $28 for NT2)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Clear_Nametable_Short:  ; $FE02
    LDA PPU_STAT        ;
    LDA #$00        ;
    STA PPU_CTL1        ; Most likely most importantly to prevent any more Resets

    LDA Temp_Var1      ; Restore A (from Reset_PPU_Clear_Nametables, this is $20 or $28, Nametable 0 or Nametable 2)
    STA PPU_VRAM_ADDR   ; Write this as high byte VRAM address select
    LDA #$00
    STA PPU_VRAM_ADDR   ; $00 as low byte for VRAM address (Reset_PPU_Clear_Nametables selects nametable 1 or 2)

    LDX #$03     ; X = 3
    LDY #$c0     ; Y = $C0
    LDA ClearPattern     ; A = ClearPattern
PRG031_FE1B:
    STA PPU_VRAM_DATA   ; Write this pattern

    DEY      ; Y--
    BNE PRG031_FE1B  ; While Y <> 0, loop

    DEX      ; X--
    BNE PRG031_FE1B  ; While X <> 0, loop!

    RTS      ; Return

; FIXME: Anybody want to claim this?
; Seems to clear the screen based on specific Vert_Scroll values
PRG031_FE25:    .byte $00, $30, $70, $B0, $EF

    ; High and Low VRAM Addresses
PRG031_FE2A:    .byte $20, $20, $21, $22, $28
PRG031_FE2F:    .byte $00, $C0, $C0, $C0, $00

; $FE34
    LDY #$04    ; Y = 4
    LDA Vert_Scroll
PRG031_FE38:
    CMP PRG031_FE25,Y
    BEQ PRG031_FE40  ; If Vert_Scroll = this value, jump to PRG031_FE40

    DEY      ; Y--
    BPL PRG031_FE38  ; While Y >= 0, loop

PRG031_FE40:

    ; Load FIXME values -> Temp_Var1/2
    LDA PRG031_FE2A,Y
    STA Temp_Var1
    LDA PRG031_FE2F,Y
    STA Temp_Var2

    LDY #$00     ; Y = 0
    LDX #$03     ; X = 3

    LDA Vert_Scroll
    CMP #$ef
    BEQ PRG031_FE58  ; If Vert_Scroll = $EF (bottom of horizontal scroll level), jump to PRG031_FE58

    LDY #$20     ; Y = $20
    LDX #$04     ; X = 4

PRG031_FE58:
    LDA PPU_STAT

    ; Disable display
    LDA #$00
    STA PPU_CTL1
PRG031_FE60:
    ; Set VRAM High/Low Addresses
    LDA Temp_Var1
    STA PPU_VRAM_ADDR
    LDA Temp_Var2
    STA PPU_VRAM_ADDR

PRG031_FE6A:
    LDA ClearPattern     ; Get the clearing pattern
    STA PPU_VRAM_DATA    ; Store it

    DEY      ; Y--
    BNE PRG031_FE76  ; If Y <> 0, jump to PRG031_FE76

    DEX      ; X--
    BEQ PRG031_FE98  ; If X = 0, jump to PRG031_FE98 (RTS)

PRG031_FE76:

    ; Next VRAM byte
    LDA Temp_Var2
    CLC
    ADC #$01
    STA Temp_Var2
    LDA Temp_Var1
    ADC #$00
    STA Temp_Var1

    CMP #$23
    BNE PRG031_FE6A  ; If haven't possibly hit the end of the nametable, jump to PRG031_FE6A

    LDA Temp_Var2
    CMP #$c0
    BNE PRG031_FE6A  ; If haven't hit the end of the nametable, jump to PRG031_FE6A

    ; Set address to second nametable
    LDA #$28
    STA Temp_Var1
    LDA #$00
    STA Temp_Var2

    JMP PRG031_FE60 ; Loop!

PRG031_FE98:
    RTS      ; Return
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DynJump
;
; A special subroutine for allowing a dynamic jump
; based on a LUT using the index specified by 'A'.
;
; To setup a dynamic call, the rules are fairly simple:
; Define a hook function which simply JSRs to this function,
; and immediately following that JSR put your LUT based on
; absolute addresses to all functions that should be called:
;
; My_DynJump:
;   JSR DynJump
;   .word $8123, $8456, $8789   ; Based on 'A', jump to $8123 (0), $8456 (1), $8789 (2)
;
; This works since the return address is gobbled up by DynJump, so you will
; never return to the "JSR DynJump" line!
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
DynJump:    ; $FE99
    ASL A       ; A << 1 (turned into an index)
    TAY     ; Y = A

    ; The old return address to this call is pulled and stored
    ; This will address the bytes that immediately followed the
    ; JSR instruction that put us here...
    PLA         ; Pull A
    STA Temp_Var1      ; Temp_Var1 = pulled A
    PLA         ; Pull A
    STA Temp_Var2      ; Temp_Var2 = pulled A

    ; REMEMBER: Since the return address was pulled, the next RTS that
    ; we happen to encounter will put us back to the call before the
    ; call that put us here at DynJump...

    INY         ; Need to increment Y (because the return address is at the last byte of the JSR)
    LDA (Temp_Var1),Y   ; Gets the byte here (address high)
    STA Temp_Var3      ; Stored into Temp_Var3
    INY         ; Y++
    LDA (Temp_Var1),Y   ; Gets the byte here (address low)
    STA Temp_Var4      ; Stores the byte into Temp_Var4
    JMP (Temp_Var3)     ; Jump to [Temp_Var4][Temp_Var3]


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Read_Joypads
;
; This subroutine reads the status of both joypads
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Read_Joypads_UnkTable:
    .byte   $00, $01, $02, $00, $04, $05, $06, $04, $08, $09, $0A, $08, $00, $01, $02, $00

Read_Joypads:

    ; Read joypads
    LDY #$01     ; Joypad 2 then 1

PRG031_FEC0:
    JSR Read_Joypad  ; Read Joypad Y

    ; FIXME: I THINK this is for switch debouncing??
PRG031_FEC3:
    LDA Temp_Var1   ; Pull result out of $00 -> A
    PHA      ; Push A
    JSR Read_Joypad  ; Read Joypad
    PLA      ; Pull A
    CMP Temp_Var1   ; Check if same
    BNE PRG031_FEC3  ; If not, do it again

    ORA Temp_Var2   ;
    PHA      ; Push A
    AND #$0f     ; A &= $0F
    TAX      ; A -> X
    PLA      ; Pull A
    AND #$f0     ; A &= $F0

    ORA Read_Joypads_UnkTable,X  ; FIXME: A |= Read_Joypads_UnkTable[X]
    PHA         ; Save A
    STA Temp_Var3      ; Temp_Var3 = A
    EOR Controller1,Y   ;
    AND Temp_Var3      ;
    STA Controller1Press,Y  ; Figures which buttons have only been PRESSED this frame as opposed to those which are being held down
    STA Pad_Input      ;
    PLA         ; Restore A
    STA Controller1,Y   ;
    STA Pad_Holding     ;
    DEY      ; Y--
    BPL PRG031_FEC0  ; If Y hasn't gone negative (it should just now be 0), Read other joypad

    ; Done reading joypads
    LDY Player_Current
    BEQ PRG031_FF11  ; If Player_Curren = 0 (Mario), jump to PRG031_FF11

    LDA Controller1
    AND #$30
    STA Temp_Var1
    LDA Controller2
    AND #$cf
    ORA Temp_Var1
    STA Pad_Holding
    LDA Controller1Press
    AND #$30
    STA Temp_Var1
    LDA Controller2Press
    AND #$cf
    ORA Temp_Var1
    STA Pad_Input

PRG031_FF11:
    RTS      ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Read_Joypad
;
; This subroutine does some tricky business to read out the joypad
; into Temp_Var1 / Temp_Var2
; Register Y should be 0 for Joypad 1 and 1 for Joypad 2
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Read_Joypad:    ; $FF12

    ; Joypad reading is weird, and actually requires 8 accesses to the joypad I/O to get all the buttons:
    ; Read #1: A
    ;      #2: B
    ;      #3: Select
    ;      #4: Start
    ;      #5: Up
    ;      #6: Down
    ;      #7: Left
    ;      #8: Right

    ; This Resets BOTH controllers
    LDA #$01     ; A = 1 (strobe)
    STA JOYPAD   ; Strobe joypad 1 (hi)
    LSR A        ; A = 0 (clear), 1 -> Carry
    STA JOYPAD   ; Clear strobe joypad 1

    ; Needs cleanup and commentary, but basically this does 8 loops to
    ; read all buttons and store the result for return
    LDX #$08     ; X = 8
Read_Joypad_Loop:
    LDA JOYPAD,Y     ; Get joypad data
    LSR A
    ROL Temp_Var1
    LSR A
    ROL Temp_Var2
    DEX
    BNE Read_Joypad_Loop     ; Loop until 8 reads complete

    RTS      ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; IntReset
; Game begins here...
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IntReset:
    SEI      ; Disable maskable interrupts
    CLD      ; Clear decimal (no BCD math, not there should be anyway)
    LDA #$00     ;
    STA PPU_CTL2     ; Most likely mainly to make BG and SPRITES invisible
    LDA #$08     ;
    STA PPU_CTL1     ; Sprites in Pattern Table 2
    LDX #$02     ; X = 2

VBlank_Wait_Loop:
    LDA PPU_STAT
    BPL VBlank_Wait_Loop    ; If VBlank NOT reported as occuring, loop around and check again!

    DEX         ; X--
    BNE VBlank_Wait_Loop    ; X starts at 2, and goes to 1; so check once more?

    DEX      ; Effectively, X = $FF
    TXS      ; X -> Stack Pointer (NMI stack)

    LDA #MMC3_2K_TO_PPU_0000
    STA MMC3_COMMAND    ; Command MMC3 to change out first 2K of PPU
    LDY #$00     ; Y = 0
    STY PPU_SCROLL   ; Horizontal scroll = 0
    STY PPU_SCROLL   ; Vertical scroll = 0
    STY MMC3_SRAM_EN ; Disable MMC3 SRAM (?)
    STY MMC3_IRQDISABLE ; Disable MMC3 IRQ generation

    LDA #%00001111   ;
    ;STA PAPU_EN  ; Enable rectangle wave 1 & 2, triangle, and noise channels
    LDA #$00     ;
    ;STA PAPU_MODCTL  ; disable DMC IRQs

    ; Any write to $4017 resets both the frame counter, and the clock divider.
    ; Sometimes, games will write to this register in order to synchronize the
    ; sound hardware's internal timing, to the sound routine's timing (usually
    ; tied into the Reset code). The frame IRQ frequency is slightly smaller than
    ; the PPU's vertical retrace frequency, so you can see why games would desire
    ; this syncronization.

    LDA #$40     ;
    STA FRAMECTR_CTL ; disable APU frame IRQ

    LDA PPU_STAT

    LDA #16      ; A = 16
    TAX      ; X = 16

    ; The following writes 16 twice to PPU_VRAM_ADDR a total of 16 times
    ; Not sure what the point of this is?  Must be some kind of hardware thing??
PRG031_FF80:
    STA PPU_VRAM_ADDR    ;
    STA PPU_VRAM_ADDR    ;
    EOR #$00     ; Do nothing??
    DEX      ; X--
    BNE PRG031_FF80  ; While X > 0, loop

    LDA #$01     ;
    STA MMC3_MIRROR  ; MMC3 command for Vertical mirroring
    LDA #$80     ;
    STA MMC3_SRAM_EN ; Re-enable MMC3 SRAM (?)

    ; Clear $07FF - $0000, excluding $01xx
    LDY #$07
    JSR Clear_RAM_thru_ZeroPage

    LDA #25
    STA PAGE_C000
    LDA #24
    STA PAGE_A000
    JSR PRGROM_Change_Both2     ; Change A000 to page 25 and C000 to page 24

    ; NOPs?
    NOP
    NOP
    NOP

    JMP IntReset_Part2  ; Rest of Reset continues in the $8000 bank...

PT2_Full_CHRROM_Switch:  ; $FFAD
    ; This subroutine does a full pattern table switchout
    LDY #$05     ; Loop Y from 5 to 0, effecting all pattern selections

PT2_Full_CHRROM_Loop:
    TYA      ; A = Y
    ORA #$40     ; A = 5 | $40 = $45 (When 5, MMC3_1K_TO_PPU_1C00; decrements thru other pages)
    STA MMC3_COMMAND ; Set MMC3 command
    LDA PatTable_BankSel,Y ; Offset into the Pattern Table 2 LUT for this page
    STA MMC3_PAGE    ; Set MMC3 page
    DEY      ; Y--
    BPL PT2_Full_CHRROM_Loop     ; While Y >= 0, loop!

    RTS      ; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PRGROM_Change_Both2
;
; This subroutine sets both PRG ROM pages A000 and C000 together.
; It also writes to $0721, apparently to allow where it returns to
; reissue the MMC3 command (FIXME reason yet unknown ???)
;   A000 is set to the page value found at RAM location PAGE_A000
;   C000 is set to the page value found at RAM location PAGE_C000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PRGROM_Change_Both2:    ; $FFBF
    JSR PRGROM_Change_C000      ; Change C000 first
    ; Continues into PRGROM_Change_A000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PRGROM_Change_A000
;
; This subroutine sets the PRG ROM page at C000
;   C000 is set to the page value found at RAM location PAGE_A000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PRGROM_Change_A000:         ; $FFC2
    LDA #MMC3_8K_TO_PRG_A000    ; Changing PRG ROM at A000
    STA PAGE_CMD            ; FIXME: Store @ PAGE_CMD
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA PAGE_A000           ; Page @ PAGE_A000
    STA MMC3_PAGE           ; Set MMC3 page
    RTS             ; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PRGROM_Change_C000
;
; This subroutine sets the PRG ROM page at A000
;   A000 is set to the page value found at RAM location PAGE_C000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PRGROM_Change_C000: ; $FFD1
    LDA #MMC3_8K_TO_PRG_C000    ; Changing PRG ROM at C000
    STA PAGE_CMD            ; FIXME: Store @ PAGE_CMD
    STA MMC3_COMMAND        ; Set MMC3 command
    LDA PAGE_C000           ; Page @ PAGE_C000
    STA MMC3_PAGE           ; Set MMC3 page
    RTS             ; Return

