image: fortenbt/smb3-build:1

aliases:
  build:
    script:
      - make
      - sha256sum --check smb3sum.txt
  bhop:
    script:
      - make bhop
  expanded:
    script:
      - make expanded
  stock:
    script:
      - make stock
      - sha256sum --check smb3sum.txt
  clean:
    script: make clean
